# Generated by Django 2.1.5 on 2019-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='newuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.CharField(blank=True, max_length=20)),
                ('phone', models.IntegerField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
