# Generated by Django 2.1.5 on 2019-01-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190110_1033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='admin_new',
        ),
    ]
