# Generated by Django 2.1.5 on 2019-01-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20190111_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_new',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='newuser',
            name='fname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
